---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/staging/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-example
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespace.my-namespace
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/staging/my-namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-example
  targetNamespace: my-namespace
