---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
spec:
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
      version: '1.6.8'
  interval: 1m0s
  values:
    imageTag: "5.7.29"
