---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: stable
      version: '1.6.8'
  interval: 1m0s
  targetNamespace: default
  values:
    imageTag: "5.7.29"
