---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: default-namespace
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/staging/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux2-example

